"""roles

Revision ID: 2475ea6f2708
Revises: b444735c148f
Create Date: 2025-11-03 15:19:05.983359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
pg = postgresql

# revision identifiers, used by Alembic.
userrole_enum = pg.ENUM('manager', 'employee', name='userrole', create_type=False)

revision: str = '2475ea6f2708'
down_revision: Union[str, Sequence[str], None] = 'b444735c148f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', userrole_enum, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', postgresql.ENUM('manager', 'employee', name='userrole'), autoincrement=False, nullable=False))
    op.drop_table('user_roles')
    # ### end Alembic commands ###
