"""Termination status

Revision ID: 2ffcf64bf424
Revises: 3da6cf68bf45
Create Date: 2025-11-03 15:44:34.504227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ffcf64bf424'
down_revision: Union[str, Sequence[str], None] = '3da6cf68bf45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'termination_status')
    op.drop_column('employee', 'termination_date')
    op.drop_column('employee', 'employment_status')
    op.drop_column('employee', 'hire_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('employment_status', postgresql.ENUM('ACTIVE', 'TERMINATED', 'RETIRED', 'RESIGNED', 'SUSPENDED', 'OTHER', name='employmentstatus'), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('termination_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('termination_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
