"""Termination status 3

Revision ID: 35f68a14e007
Revises: 2ffcf64bf424
Create Date: 2025-11-03 15:54:32.658736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f68a14e007'
down_revision: Union[str, Sequence[str], None] = '2ffcf64bf424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure enum type exists
    employment_status_enum = sa.Enum('ACTIVE', 'TERMINATED', 'RETIRED', 'RESIGNED', 'SUSPENDED', 'OTHER', name='employmentstatus')
    employment_status_enum.create(op.get_bind(), checkfirst=True)

    # Add column as nullable first
    op.add_column('employee', sa.Column('employment_status', employment_status_enum, nullable=True))
    # Fill with default value
    op.execute("UPDATE employee SET employment_status = 'ACTIVE' WHERE employment_status IS NULL")
    # Alter to NOT NULL
    op.alter_column('employee', 'employment_status', nullable=False)
    op.add_column('employee', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('employee', sa.Column('termination_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'termination_date')
    op.drop_column('employee', 'hire_date')
    op.drop_column('employee', 'employment_status')
    # ### end Alembic commands ###
