"""Enum

Revision ID: 3da6cf68bf45
Revises: 2475ea6f2708
Create Date: 2025-11-03 15:34:38.905143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
employment_status_enum = sa.Enum(
    "ACTIVE", "TERMINATED", "RETIRED", "RESIGNED", "SUSPENDED", "OTHER",
    name="employmentstatus"
)
employment_status_enum.create(op.get_bind(), checkfirst=True)
revision: str = '3da6cf68bf45'
down_revision: Union[str, Sequence[str], None] = '2475ea6f2708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'employment_status',
               existing_type=sa.VARCHAR(),
               type_= employment_status_enum,
               existing_nullable=False,
                postgresql_using="employment_status::employmentstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'employment_status',
               existing_type=sa.Enum('ACTIVE', 'TERMINATED', 'RETIRED', 'RESIGNED', 'SUSPENDED', 'OTHER', name='employmentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
