"""Removed grade

Revision ID: 7a862b4a2b75
Revises: a1f4b2fbda79
Create Date: 2025-10-31 09:39:38.155528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a862b4a2b75'
down_revision: Union[str, Sequence[str], None] = 'a1f4b2fbda79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
