"""User schema

Revision ID: 86e83be384fc
Revises: 7a862b4a2b75
Create Date: 2025-10-31 10:38:52.997468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e83be384fc'
down_revision: Union[str, Sequence[str], None] = '7a862b4a2b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employee_user_id_fkey'), 'employee', type_='foreignkey')
    op.drop_column('employee', 'user_id')
    op.create_foreign_key(None, 'user', 'employee', ['email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.add_column('employee', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('employee_user_id_fkey'), 'employee', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
