"""payroll_upgrade 2

Revision ID: d831516b559c
Revises: fab6884fcc0e
Create Date: 2025-11-05 11:49:13.873738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd831516b559c'
down_revision: Union[str, Sequence[str], None] = 'fab6884fcc0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_record', sa.Column('payroll_year', sa.Integer(), nullable=False))
    op.add_column('payroll_record', sa.Column('payroll_month', sa.Integer(), nullable=False))
    op.drop_column('payroll_record', 'year')
    op.drop_column('payroll_record', 'month')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_record', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payroll_record', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payroll_record', 'payroll_month')
    op.drop_column('payroll_record', 'payroll_year')
    # ### end Alembic commands ###
