"""payroll_upgrade

Revision ID: fab6884fcc0e
Revises: da968855fee0
Create Date: 2025-11-05 11:07:06.958404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab6884fcc0e'
down_revision: Union[str, Sequence[str], None] = 'da968855fee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_record', sa.Column('employee_full_name', sa.String(length=128), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_national_id', sa.String(length=32), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_position', sa.String(length=64), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_department', sa.String(length=64), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_base_salary', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_net_salary', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_net_income', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_base_before_taxes', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_tax_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_health_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_health_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_pension_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_pension_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_other_deductions', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_worked_days', sa.Integer(), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_leave_days', sa.Integer(), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_meal_ticket_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_other_benefits', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('payroll_record', sa.Column('employee_bonus_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_column('payroll_record', 'total_deductions')
    op.drop_column('payroll_record', 'gross_pay')
    op.drop_column('payroll_record', 'net_pay')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_record', sa.Column('net_pay', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('payroll_record', sa.Column('gross_pay', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('payroll_record', sa.Column('total_deductions', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_column('payroll_record', 'employee_bonus_amount')
    op.drop_column('payroll_record', 'employee_other_benefits')
    op.drop_column('payroll_record', 'employee_meal_ticket_amount')
    op.drop_column('payroll_record', 'employee_leave_days')
    op.drop_column('payroll_record', 'employee_worked_days')
    op.drop_column('payroll_record', 'employee_other_deductions')
    op.drop_column('payroll_record', 'employee_pension_percent')
    op.drop_column('payroll_record', 'employee_pension_amount')
    op.drop_column('payroll_record', 'employee_health_amount')
    op.drop_column('payroll_record', 'employee_health_percent')
    op.drop_column('payroll_record', 'employee_tax_amount')
    op.drop_column('payroll_record', 'employee_tax_percentage')
    op.drop_column('payroll_record', 'employee_base_before_taxes')
    op.drop_column('payroll_record', 'employee_net_income')
    op.drop_column('payroll_record', 'employee_net_salary')
    op.drop_column('payroll_record', 'employee_base_salary')
    op.drop_column('payroll_record', 'employee_department')
    op.drop_column('payroll_record', 'employee_position')
    op.drop_column('payroll_record', 'employee_national_id')
    op.drop_column('payroll_record', 'employee_full_name')
    # ### end Alembic commands ###
